$ANSIBLE_VAULT;1.1;AES256
37346437313132666330313965663266313362653932323634333837653065653263336133396662
3937613762316164646133303863656233323837656664300a643838373965396264636162386334
66386639623730626465393936396332316539303864623231656235343738316563353763366162
3333306539663135610a633739616663373738326165396135323934646532363363356636613663
66663432633139303863653839663235373062396237343138363064646561313963306435313735
32646335633864363035616134653430613363656436306330616538303765666165623863623962
32326538663463386164653334303435356239643965366330616437613333323235666436303637
37323431613634313139656661316533333866373061353864323838396566383735666231623630
33393661363364643562316165633639306139363462363638643832656638633135
