$ANSIBLE_VAULT;1.1;AES256
32373433366335383764663164306561373264333234373864663264363766353536613435663438
3565653333313662343831626463313333353962343639390a343339653436336561666531356466
34323836663330326137356366343166366631346539306335336564303335323139353138346665
3731656663353161340a633837373733313431343935323536313765336361346433393338326535
61623965393132313131623837393263393431363066643235616239343263636536386662346230
66653536316235633464363337303563643435323363303136336431623364656635366432633961
63346361666361376536623138653133316535393830353363306630353239616235373266633766
36376164626564303531333133356130326265343035613635386333303138626432393634343562
63303366366334326139663261383330643532356431663930353433306630663434
