$ANSIBLE_VAULT;1.1;AES256
33316234366565353233393061633438346439323435303466616463306535386265623561656236
6635333837383763313837616132313466383539643465390a366234666531613763346638373466
30613938333062353136656632396433313930323436653735316165383062353536346534303634
6464313931646333300a363332333834663332633935663266313664353532376330626165393661
61303666396136326562633061386564326564613034636534343562353731356262343663326536
61303166326135386134316239383736616365353363363763616630393261653736383762613565
63373232663032306266633863353962346638663733656562313364646238636538643634663436
37626137323435626634353966333335306262383864356461626365666530383561663035643964
39663836386637656531383661303530393964303233323237666462666666313833303137393635
30366465333834363835643537363166373431313930663361663164326235653534643933353064
39396663343634396237653839356564333766666434326336636135626337633933303736353563
34613764393764626537393931656132363061663239393730656231666661396135633633663239
37313964663939333535643636363139656234316333323835386231393664613264356333636166
34343233366561393033623064636562383966326563333236643361303663643262623134363031
30343132613739386335343536383361306630336461623730616237393135306266323363396138
64623064313634626537656264343930626331343039633635376263346435643638353562343834
33616535396139316331666530643033623834646263343932643264343930303362653465326631
6637666365656438393231616266336435626564333638643431
