---
- name: Install podman when os is Debian
  become: true
  ansible.builtin.apt:
    name:
      - podman
      - podman-compose
      - iptables
    state: present
    update_cache: true
  when: ansible_facts['distribution'] == 'Debian'
