---
- name: Create filesystem
  become: true
  ansible.builtin.file:
    path: /opt/recipes
    owner: sysadm
    group: sysadm
    mode: '0755'
    state: directory

- name: Create systemd filesystem
  become: true
  ansible.builtin.file:
    path: /home/sysadm/.config/systemd/user 
    owner: sysadm
    group: sysadm
    mode: '0755'
    state: directory

- name: Rollout .env
  ansible.builtin.template:
    src: ../templates/recipes-env.j2
    dest: /opt/recipes/.env
    owner: sysadm
    group: sysadm
    mode: '0644'
    backup: false

- name: Rollout compose file
  ansible.builtin.template:
    src: ../templates/recipes-compose.j2
    dest: /opt/recipes/docker-compose.yml
    owner: sysadm
    group: sysadm
    mode: '0644'
    backup: true

- name: Enable linger for sysadm
  become: true
  ansible.builtin.command: "loginctl enable-linger sysadm"

- name: Place systemd unit in sysadm user dir
  become: true
  become_user: sysadm
  ansible.builtin.template:
    src: recipes.service.j2
    dest: "/home/sysadm/.config/systemd/user/podman-compose@recipe.service"
    mode: '0644'

- name: Reload user systemd daemon
  become: true
  become_user: sysadm
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true

- name: Enable and start podman-compose instance
  become: true
  become_user: sysadm
  ansible.builtin.systemd:
    name: "podman-compose@recipe.service"
    scope: user
    enabled: true
    state: started

