---
- name: Rollout .env
  ansible.builtin.template:
    src: ../templates/recipes-env.j2
    dest: /opt/recipes/.env
    owner: sysadm
    group: sysadm
    mode: '0644'
    backup: true

- name: Rollout compose file
  ansible.builtin.template:
    src: ../templates/recipes-compose.j2
    dest: /opt/recipes/docker-compose.yml
    owner: sysadm
    group: sysadm
    mode: '0644'
    backup: true

- name: Place systemd unit
  become: true
  ansible.builtin.template:
    src: recipes.service.j2
    dest: /etc/systemd/system/recipes.service
    mode: '0644'
  notify: Reload systemd

- name: Enable and start service
  become: true
  ansible.builtin.systemd:
    name: recipes.service
    enabled: true
    state: started
