---
- name: Ensure ACME and TLS directory structure exists
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ acme_user }}"
    group: "{{ web_user }}"
    mode: '775'
  loop:
    - { path: "{{ tls_base_dir }}" }
    - { path: "{{ tls_base_dir }}/rsa" }
    - { path: "{{ tls_base_dir }}/ecdsa" }
  tags: [tls]


- name: Ensure ACME http-01 challenge webroot exists
  become: true
  ansible.builtin.file:
    path: "{{ acme_webroot }}/.well-known/acme-challenge"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '775'
  tags: [tls]

- name: Ensure permissions for ACME webroot
  become: true
  ansible.builtin.file:
    path: "{{ acme_webroot }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    recurse: true
  tags: [tls]

- name: Deploy nginx vhost for ACME http-01 gateway
  become: true
  ansible.builtin.copy:
    src: HttpGateway.conf
    dest: /etc/nginx/conf.d/HttpGateway.conf
    owner: root
    group: root
    mode: "775"
  notify: Reload nginx
  tags: [tls, nginx]

- name: Issue certificate with acme.sh
  become_user: "{{ acme_user }}"
  ansible.builtin.command:
    cmd: >
      ~/.acme.sh/acme.sh --issue
      -d {{ domain }}
      --keylength 4096
      -w {{ acme_webroot }}
      --key-file {{ tls_base_dir }}/rsa/key.pem
      --ca-file {{ tls_base_dir }}/rsa/ca.pem
      --cert-file {{ tls_base_dir }}/rsa/cert.pem
      --fullchain-file {{ tls_base_dir }}/rsa/fullchain.pem
      --reloadcmd "sudo /bin/systemctl reload nginx.service"
    creates: "{{ tls_base_dir }}/rsa/fullchain.pem"
  notify: Reload nginx
  tags: [tls,ca-issue]

- name: Issue ECDSA with acme.sh
  become_user: "{{ acme_user }}"
  ansible.builtin.command:
    cmd: >
      ~/.acme.sh/acme.sh --issue
      -d {{ domain }}
      --keylength ec-384
      -w {{ acme_webroot }}
      --key-file {{ tls_base_dir }}/ecdsa/key.pem
      --ca-file {{ tls_base_dir }}/ecdsa/ca.pem
      --cert-file {{ tls_base_dir }}/ecdsa/cert.pem
      --fullchain-file {{ tls_base_dir }}/ecdsa/fullchain.pem
      --reloadcmd "sudo /bin/systemctl reload nginx.service"
    creates: "{{ tls_base_dir }}/ecdsa/fullchain.pem"
  notify: Reload nginx
  tags: [tls,ecdsa-issue]

- name: Ensure dhparams directory exists
  ansible.builtin.file:
    path: /etc/nginx/dhparams
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true
  
- name: Generate Diffie-Hellman parameters with the default size (4096 bits)
  become: true
  community.crypto.openssl_dhparam:
    path: /etc/nginx/dhparams/dhparams.pem