---
- name: Ensure ACME and TLS directory structure exists
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: 755
  loop:
    - { path: "{{ tls_base_dir }}" }
    - { path: "{{ tls_base_dir }}/nextcloud" }
    - { path: "{{ tls_base_dir }}/rsa" }
    - { path: "{{ tls_base_dir }}/ecdsa" }
  tags: [tls]


- name: Ensure ACME http-01 challenge webroot exists
  become: true
  ansible.builtin.file:
    path: "{{ acme_webroot }}/.well-known/acme-challenge"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '775'
  tags: [tls]

- name: Ensure permissions for ACME webroot
  become: true
  ansible.builtin.file:
    path: "{{ acme_webroot }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    recurse: true
  tags: [tls]

- name: Deploy nginx vhost for ACME http-01 gateway
  become: true
  ansible.builtin.copy:
    src: HttpGateway.conf
    dest: /etc/nginx/conf.d/HttpGateway.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx
  tags: [tls, nginx]
