---
- name: Setup homeserver
  hosts: homeserver
  remote_user: sysadm

  tasks:
    - name: Update packages
      ansible.builtin.import_tasks:
        file: tasks/update_packages.yml
    - name: Install packages
      become: true
      ansible.builtin.import_tasks:
        file: tasks/install_packages.yml
    - name: Setup filesystem
      ansible.builtin.import_tasks:
        file: tasks/setup_filesystem.yml
