---
- name: check os is ubuntu
  ansible.builtin.fail:
    msg: "wrong os"
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install requried packages
  become: true
  ansible.builtin.apt:
    name:
      - podman
      - podman-compose
      - lvm2
    state: present
    update_cache: true
